spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strong_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug

protect:
  attempt:
    brute-force: 3
