spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: workload_local
      username: root
      password: password
      authentication-database: admin

logging:
  level:
    root: info
