server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: strong-service
          uri: lb://strong-service
          predicates:
            - Path=/strong/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            filter: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
